blueprint:
  name: Rollladen -  - Virtuell synchronisieren
  description: Rollladen viertuell auf die Position des physischen setzen, wenn physisches betätigt sind
  domain: automation
  input:
    shutter_virtual:
      name: Rollo virtuell
      description: Virtuelles Rollo, welches angepasst wird
      selector:
        entity:
          filter:
            - domain: cover
            - device_class: shutter
    shutter_physical:
      name: Rollo phyisch
      description: Physisches Rollo, welches der Auslöser ist
      selector:
        entity:
          filter:
            - domain: cover
            - device_class: shutter   

mode: queued
max: 15


trigger:
  - platform: state
    entity_id: !input shutter_physical
    to: closing
  - platform: state
    entity_id: !input shutter_physical
    to: opening


action:
  - if:
      - condition: state
        entity_id: !input shutter_physical
        state: closing
    then:
      - service: cover.close_cover
        target:
          entity_id: !input shutter_virtual
  - if:
      - condition: state
        entity_id: !input shutter_physical
        state: opening
    then:
      - service: cover.open_cover
        target:
          entity_id: !input shutter_virtual
